### PR TITLE
Extract HTTP status code handling to a client fitler

### PR DESCRIPTION
**Pull request by hamishmorgan**
This is part 2 of my exciting and epic adventures; in which a a heroic programmer sorts out the network connection code. If you haven't yet read part 1 (and in particular if it isn't merged yet) you should go check that out first: #27 

Today the hero of the story has has extracted the HTTP response code handling into another client filter. Responses for which we shouldn't even both trying to read the data, convert to exceptions that are caught further up the application stack.

Stay tuned for more gripping instalments

### CODE REVIEW

**Comment by jstanier** [comment]
Ready for a rebase on this one.

**Comment by hamishmorgan** [comment]
Thanks.

**Comment by hamishmorgan** [comment]
Coverage dripped because I deleted the tests of the deleted code. This left a small amount of extra code uncovered, but it wasn't really testing anything before in any significant way.... So I think the testing is better, even though the coverage is worse.

**Comment by jstanier** [comment]
:+1:

**Pull request merged**
