### PR TITLE
NT Added coverals and maven release badges

### LINKED ISSUE #2: Unit test coverage with coveralls

### PR DESCRIPTION
**Pull request by hamishmorgan**
- Added shields for the latest version available on maven central (Currently there isn't one :/)
- Added badge for coveralls coverage
- Added maven build plugin for coveralls 

It looks like this: https://github.com/hamishmorgan/robots/blob/More-badges/README.md

_Don't merge until we are sure this works_

Closes #2

### CODE REVIEW

**Comment by hamishmorgan** [comment]
Coveralls shield for this PR branch: [Coverage Status](https://coveralls.io/r/BrandwatchLtd/robots?branch=More-badges)

**Comment by jstanier** [comment]
For some reason it's still not on maven central. Let me have a look into why this is now.

**Comment by jstanier** [comment]
OK, so it turns out I didn't click the "Release" button after what we did on Friday. I've now clicked it, and the release seemed to work and it disappeared from the staging repositories on Sonatype Nexus. Let's wait to see if it turns up in the next few hours.

Is there a reason why the Coveralls shield for this PR branch reads "unknown"?

**Comment by jstanier** [comment]
Usually you need to specify the encrypted coveralls key somewhere, either in the `.travis.yml` file, or in a plug-in like this one: https://github.com/trautonen/coveralls-maven-plugin

It's worth mentioning that I found it quite hard to decide on what Travis/Coveralls best practice was, so your guess may be as good as mine here.

**Comment by jstanier** [comment]
It's on maven central now. The badge will need to change to use the search string `g:"com.brandwatch" AND a:"robots-parent"`.

**Comment by hamishmorgan** [comment]
Many points to reply to:

Thanks for sorting out the release - I may do another bug fix release soon to check I've got it worked out. Also want to see if it integrates with the release plugin, because manual tagging is a pain.

I don't know why the first shield is "unknown" - it wasn't when I put it there. Doesn't matter now though.

I've got coveralls working without the key... apparently you don't need it with Travic CI for some reason. Not sure if this is the best way either. The documentation is not great imo (lots of contradictory instructions, and it all depends on what combination of tools you are using).

Fixed the maven artifact id in the shield. Thanks

~~I think this is probably good to merge, unless you can think of something else.~~

**Comment by hamishmorgan** [comment]
Why there are so many messages from coveralls: It seems to be running once for each JDK, which isn't ideal...

**Comment by hamishmorgan** [comment]
Yay! Ok it only runs once now. I think this is good to go again. :-)

**Pull request merged**
